- name: Boot from external disk
  hosts: raspberries
  become: true
  roles:
    - name: external-boot
      tags: external-boot

- name: Update OS
  hosts: raspberries
  become: true
  roles:
    - name: update
      tags: update
