- name: Boot from external disk
  hosts: raspberries
  become: true
  roles:
    - name: external-boot
      tags: external-boot

- name: Update OS
  hosts: raspberries
  become: true
  roles:
    - name: update
      tags: update

- name: Install docker and docker-compose
  hosts: raspberries
  become: true
  roles:
    - name: docker
      tags: docker

- name: Install piVCCU
  hosts: raspberries
  become: true
  roles:
    - name: pivccu
      tags: pivccu

- name: Install MQTT
  hosts: raspberries
  become: true
  roles:
    - name: mqtt
      tags: mqtt

# keyboard layout, US localization
