- name: Install
  apt:
    name:
      - pivccu3
    state: latest

- name: Force binding piVCCU's network interface to the br0 bridge
  # Docker will create other br* interfaces that we cannot use.
  lineinfile:
    path: /etc/piVCCU3/lxc.config
    regexp: ^(lxc.network.link =)
    line: \1 br0
    backrefs: true
    backup: yes
    state: present
  register: bridge_configured

- name: Restart service
  systemd:
      name: pivccu
      state: restarted
  when: bridge_configured.changed

- name: Get information
  command:
    pivccu-info
  changed_when: false
  register: pivccu_info

- name: Show information
  debug:
    var: pivccu_info.stdout_lines
  changed_when: false

- name: Verify
  fail:
    msg: piVCCU appears not to be running.
  when: not 'RUNNING' in pivccu_info.stdout
