- name: Remove dhcpcd5
  apt:
    name:
      - dhcpcd5
    state: absent

- name: Install bridge-utils
  apt:
    name:
      - bridge-utils
    state: latest

- name: Get ethernet interfaces
  shell: >-
    ip --brief link show |
      cut --delimiter ' ' --fields 1 |
      grep --regexp '^e.*'
  changed_when: false
  register: eth_interfaces

- name: Copy network configuration file for {{ eth_interfaces.stdout_lines | first }}
  template:
    src: ../templates/network-interfaces.j2
    dest: /etc/network/interfaces
  notify: Reboot

- name: Gather installed packages
  package_facts:

- name: Check if docker is installed
  set_fact:
    docker_packages: >-
      {{
        query('dict', ansible_facts.packages) |
          selectattr('key', 'match', 'docker') |
          list
      }}

- name: Enable firewall rules for docker compatibuility
  when: docker_packages | length > 0
  block:
    - name: Print docker packages
      debug:
        msg: >-
          {{ docker_packages | length }} packages named docker are installed:
          {{ docker_packages | map(attribute = 'key') | list }}

    - name: Create directory for docker service override
      file:
        path: /etc/systemd/system/docker.service.d/
        state: directory

    - name: Add firewall rules for docker compatibility before starting docker
      template:
        src: ../templates/docker-service-override.conf
        dest: /etc/systemd/system/docker.service.d/pivccu-compatibility.conf

    - name: Reload systemd
      systemd:
        daemon_reload: true
