- name: Create root directory
  file:
    path: "{{ root }}"
    state: directory
  notify: Restart service

- name: Create directories
  file:
    path: "{{ root }}/{{ item.path }}"
    state: directory
  when: item.state == 'directory'
  with_filetree: "{{ directory }}"
  loop_control:
    label: "{{ item.path }}"
  notify: Restart service

- name: Template files
  template:
    src: "{{ item.src }}"
    dest: "{{ root }}/{{ item.path | dirname }}/{{ item.path | basename | regex_replace('\\.j2$', '') }}"
    mode: preserve
    lstrip_blocks: true
  when: item.state == 'file' and (not item.path | basename == '.gitignore')
  with_filetree: "{{ directory }}"
  loop_control:
    label: "{{ item.path }}"
  notify: Restart service
