- name: Install required packages for docker-compose
  apt:
    name:
      - python3-pip
      - libffi-dev
      - libssl-dev
    state: latest

- name: Get installed pip3 packages
  shell:
    pip3 list
  changed_when: false
  register: installed_packages

- name: Install docker-compose
  command: pip3 install docker-compose
  when: not 'docker-compose' in installed_packages.stdout
