- name: Install required packages
  apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg2
    state: latest

- name: Add apt key
  apt_key:
    url: https://download.docker.com/linux/{{ ansible_distribution|lower }}/gpg
    id: 9DC858229FC7DD38854AE2D88D81803C0EBFCD88
    state: present

- name: Add apt repository
  apt_repository:
    repo: >-
      deb
      https://download.docker.com/linux/{{ ansible_distribution|lower }}
      {{ ansible_distribution_release }}
      stable
    state: present

- name: Install docker
  apt:
    name: docker-ce
    state: latest
    update_cache: true
    install_recommends: false

- name: Add current user to docker group
  user:
    name: "{{ ansible_user }}"
    groups: docker
    append: true

- name: Install required packages
  apt:
    name:
      - python3-pip
      - libffi-dev
      - libssl-dev
    state: latest

- name: Check if docker-compose is installed
  shell:
    pip3 list | grep docker-compose
  changed_when: false
  ignore_errors: true
  register: installed

- name: Install docker-compose
  command: pip3 install docker-compose
  when: installed is failed
